version: 2
updates:
  - package-ecosystem: "npm" # Replace with your package manager (e.g., npm, pip, maven, etc.)
    directory: "/"           # Directory where your package.json is located
    schedule:
      interval: "weekly"     # Can be 'daily', 'weekly', or 'monthly'
